name: Develop

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  autoformatting:
    uses: ./.github/workflows/autoformatting.yml
  testing:
    needs: autoformatting
    uses: ./.github/workflows/testing.yml
  pin_requirements:
    needs: testing
    uses: ./.github/workflows/pin_requirements.yml
  build:
    uses: ./.github/workflows/uploadpypi.yml



