name: PublishTests

on: [push]
#  release:
#    types: [published]

jobs:
#  autoformatting:
#    uses: ./.github/workflows/autoformatting.yml
#  testing:
#    needs: autoformatting
#    uses: ./.github/workflows/testing.yml
  build:
    name: Build distribution
#    needs: testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --without dev
      - name: Publish package
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}
          poetry publish --build -r testpypi