name: Develop

on:
  pull_request:
    branches:
      - 'testing-ci'
  push:
    branches:
      - 'testing-ci'

jobs:
  autoformatting:
    uses: ./.github/workflows/autoformatting.yml
  testing:
    needs: autoformatting
    uses: ./.github/workflows/testing.yml



