name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  autoformatting:
    uses: ./.github/workflows/autoformatting.yml
  testing:
    needs: autoformatting
    uses: ./.github/workflows/testing.yml
  deploy:
    needs: testing
    uses: ./.github/workflows/deploy.yml
