name: Upload Python Package

on:
  workflow_call:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Print result
      run: |
        echo "id: ${{ steps.last_release.outputs.id }}"
        echo "name: ${{ steps.last_release.outputs.name }}"
        echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
        echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
        echo "draft: ${{ steps.last_release.outputs.draft }}"
        echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
#
#    - name: Get the current release version
#      id: get_version
#      run: |
#        TAG=${{ steps.last_release.outputs.tag_name }}
#        echo "TAG: $TAG" # Debug: print the tag
#        VERSION=$(echo $TAG | sed 's/^v//')
#        echo "VERSION: $VERSION" # Debug: print the version
#        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
#
#    - name: Check environment variables
#      run: env
#
#    - name: Create VERSION file
#      run: echo "${{ env.RELEASE_VERSION }}" > VERSION
#
#    - name: Check VERSION file
#      run: cat VERSION
#
#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install build
#
#    - name: Build a binary wheel and a source tarball
#      run: python -m build
#    - name: Store the distribution packages
#      uses: actions/upload-artifact@v4
#      with:
#        name: python-package-distributions
#        path: dist/
#
#  publish-to-testpypi:
#    name: Upload release to PyPI
#    needs:
#      - build
#    runs-on: ubuntu-latest
#    environment:
#      name: testpypi
#      url: https://test.pypi.org/p/adopt-net0
#    permissions:
#      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
#    steps:
#    - name: Download all the dists
#      uses: actions/download-artifact@v4
#      with:
#        name: python-package-distributions
#        path: dist/
#    - name: Publish package distributions to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#        repository-url: https://test.pypi.org/legacy/
